name: Go

on:
  pull_request:
    branches: [ master ]
    paths:
      - internal/**.go

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install git
      run: sudo apt-get install git

    - name: Setup for private repository go get access
      run: |
        git config --global url."https://git:${{ secrets.GA_TOKEN }}@github.com/bananaumai-dev".insteadOf "https://github.com/bananaumai-dev"

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: go test -v ./...
